name: RSpec

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container: ruby:2.7.4-alpine3.14

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          bin/bundle install
      - name: RSpec
        run: |
          bin/rails db:setup RAILS_ENV=test
          bin/bundle exec rspec
        env:
          TEST_DATABASE_URL: "postgresql://postgres:password@127.0.0.1/webkansu_test"
