name: RSpec

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: RSpec
        run: |
          bin/rails db:setup RAILS_ENV=test
          bin/bundle exec rspec
        env:
          TEST_DATABASE_URL: "postgresql://postgres:password@localhost:5432/webkansu_test"
